apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rating
  template:
    metadata:
      labels:
        app: rating
    spec:
      containers:
      - name: rating
        image: jovial5/cinephile-rating:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8082