apiVersion: apps/v1
kind: Deployment
metadata:
  name: film
spec:
  replicas: 1
  selector:
    matchLabels:
      app: film
  template:
    metadata:
      labels:
        app: film
    spec:
      containers:
      - name: film
        image: jovial5/cinephile-film:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: film
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8083
  selector:
    app: film